# .travis.yml for TO-DO-LIST (Node + Docker + Render deploy using deploy hook)

language: minimal
sudo: required

services:
  - docker

env:
  global:
    # Port your backend uses inside Docker
    - PORT=3000
    # Node environment
    - NODE_ENV=production
    # MongoDB URI (set in Travis or Render as env variable for security)
    - MONGO_URI=mongodb+srv://harikaallugunti_db_user:mBirLtZj3TkQQckB@cluster0.zuwcyeo.mongodb.net/todoapp?retryWrites=true&w=majority
    # JWT secret (set in Travis or Render as env variable)
    - JWT_SECRET=your-strong-secret

before_install:
  - echo "Starting Travis CI build for TO-DO-LIST"

script:
  - echo "Building Docker image..."
  - docker build -t todo-list .

after_success:
  - echo "Deploying Docker image to Render via deploy hook..."
  # Replace this with your actual deploy hook URL
  - curl -X POST "https://api.render.com/deploy/srv-d35oko6mcj7s73a3iphg?key=MVY4UIZ4i_s"

branches:
  only:
    - main
